### ISSUE TITLE
Need support for remote and virtual Repository creation

### ISSUE THREAD

**Issue by russroy** [chef/artifactory-client#55]
Need support for remote and virtual Repository creation

```
irb(main):142:0> repo = Repository.new(key: 'russ-repo2', rclass: 'remote', url: 'http://host:port/some-repo')
=> #<Repository blacked_out: nil, description: nil, checksum_policy_type: nil, excludes_pattern: nil, handle_releases: nil, handle_snapshots: nil, includes_pattern: nil, key: "russ-repo2", max_unique_snapshots: nil, notes: nil, property_sets: nil, repo_layout_ref: nil, rclass: "remote", snapshot_version_behavior: nil, suppress_pom_consistency_checks: nil, url: "http://host:port/some-repo">
irb(main):143:0> repo.save
NoMethodError: undefined method `url' for #<Artifactory::Resource::Repository:0x007fda8aaa7aa0>
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:300:in `block in to_hash'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `each'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `inject'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:298:in `to_hash'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/base.rb:315:in `to_json'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/repository.rb:98:in `save'
    from (irb):143
    from /Users/rroy/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):144:0>
```

Or ... if you try to create a remote repo w/o the req'd url:

```
irb(main):145:0> repo = Repository.new(key: 'russ-repo2', rclass: 'remote')
=> #<Repository blacked_out: nil, description: nil, checksum_policy_type: nil, excludes_pattern: nil, handle_releases: nil, handle_snapshots: nil, includes_pattern: nil, key: "russ-repo2", max_unique_snapshots: nil, notes: nil, property_sets: nil, repo_layout_ref: nil, rclass: "remote", snapshot_version_behavior: nil, suppress_pom_consistency_checks: nil>
irb(main):146:0> repo.save
Artifactory::Error::HTTPError: The Artifactory server responded with an HTTP Error 400: `No URL defined for remote repository
'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:374:in `error'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:255:in `block in request'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/net/http.rb:746:in `start'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:245:in `request'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/client.rb:131:in `put'
    from /Users/rroy/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/artifactory-2.3.0/lib/artifactory/resources/repository.rb:98:in `save'
    from (irb):146
    from /Users/rroy/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):147:0>
```

**Comment by antoniobeyah** [comment]
@schisamo I am going to run into this soon and am willing to pickup this work, I wanted to run by my idea of how to implement though because it may be backwards incompatible.

The core idea is to create classes for each repository type (LocalRepository, VirtualRepository, RemoteRepository).  The real question becomes what to do with the existing Repository class.

We could try to maintain backwards compatibility but it might not make sense to do so.  For the existing Repository class I'm leaning towards altering its behavior to wrap the some of the current functionality (describing repositories of all types, searching, etc) but have not dug into the implications of doing so yet.  I am primarily thinking about what it will look like for the meta functions that are generated on the fly in the client class. <resource>_<method>.

This work can also encompass the issues for #56 and #57 

Any thoughts on this?

**Comment by robkinyon** [comment]
Does #69 fix this and can this be closed?

**Comment by schisamo** [comment]
@robkinyon You are correct, this should now be fixed.
