### ISSUE TITLE
Specs fail on windows

### ISSUE THREAD

**Issue by bergholdt** [chef/artifactory-client#79]
Running the test suite fails on windows in test that check on file path, on windows path does not start with '/' but include drive letter.

If windows user should contribute they must be able to pass test locally before pushing.

```
λ bundle exec rake travis:ci
C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb' --tag ~integration
Run options:
  include {:focus=>true}
  exclude {:integration=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 23668
....................FFFFFFF.................................................................................FFFFFF...................................................................................

Failures:

  1) Artifactory::Resource::Artifact#upload when the md5 is available PUTs the file with the checksum headers set
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:62:in `block (4 levels) in <module:Artifactory>'

  2) Artifactory::Resource::Artifact#upload when matrix properties are given converts "+" to "%2B"
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:96:in `block (4 levels) in <module:Artifactory>'

  3) Artifactory::Resource::Artifact#upload when matrix properties are given converts the hash into matrix properties
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:79:in `block (4 levels) in <module:Artifactory>'

  4) Artifactory::Resource::Artifact#upload when matrix properties are given converts spaces to "+" characters
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:88:in `block (4 levels) in <module:Artifactory>'

  5) Artifactory::Resource::Artifact#upload when the sha1 is available PUTs the file with the checksum headers set
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:71:in `block (4 levels) in <module:Artifactory>'

  6) Artifactory::Resource::Artifact#upload when custom headers are given passes the headers to the client
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:107:in `block (4 levels) in <module:Artifactory>'

  7) Artifactory::Resource::Artifact#upload when the artifact is a file path PUTs the file at the path to the server
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/local/path")
              got: ("D:/local/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./spec/unit/resources/artifact_spec.rb:53:in `block (4 levels) in <module:Artifactory>'

  8) Artifactory::Resource::Repository#upload when custom headers are given passes the headers to the client
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/fake/path")
              got: ("D:/fake/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./lib/artifactory/resources/repository.rb:116:in `upload'
     # ./spec/unit/resources/repository_spec.rb:184:in `block (4 levels) in <module:Artifactory>'

  9) Artifactory::Resource::Repository#upload when matrix properties are given converts the hash into matrix properties
     Failure/Error: file     = File.new(File.expand_path(local_path))

       #<File (class)> received :new with unexpected arguments
         expected: ("/fake/path")
              got: ("D:/fake/path")
        Please stub a default value first if message might be received with other args as well.
     # ./lib/artifactory/resources/artifact.rb:533:in `upload'
     # ./lib/artifactory/resources/repository.rb:116:in `upload'
     # ./spec/unit/resources/repository_spec.rb:156:in `block (4 levels) in <module:Artifactory>'

  10) Artifactory::Resource::Repository#upload when matrix properties are given converts "+" to "%2B"
      Failure/Error: file     = File.new(File.expand_path(local_path))

        #<File (class)> received :new with unexpected arguments
          expected: ("/fake/path")
               got: ("D:/fake/path")
         Please stub a default value first if message might be received with other args as well.
      # ./lib/artifactory/resources/artifact.rb:533:in `upload'
      # ./lib/artifactory/resources/repository.rb:116:in `upload'
      # ./spec/unit/resources/repository_spec.rb:173:in `block (4 levels) in <module:Artifactory>'

  11) Artifactory::Resource::Repository#upload when matrix properties are given converts spaces to "+" characters
      Failure/Error: file     = File.new(File.expand_path(local_path))

        #<File (class)> received :new with unexpected arguments
          expected: ("/fake/path")
               got: ("D:/fake/path")
         Please stub a default value first if message might be received with other args as well.
      # ./lib/artifactory/resources/artifact.rb:533:in `upload'
      # ./lib/artifactory/resources/repository.rb:116:in `upload'
      # ./spec/unit/resources/repository_spec.rb:165:in `block (4 levels) in <module:Artifactory>'

  12) Artifactory::Resource::Repository#upload when matrix properties are given converts the hash into matrix properties
      Failure/Error: file     = File.new(File.expand_path(local_path))

        #<File (class)> received :new with unexpected arguments
          expected: ("/fake/path")
               got: ("D:/fake/path")
         Please stub a default value first if message might be received with other args as well.
      # ./lib/artifactory/resources/artifact.rb:533:in `upload'
      # ./lib/artifactory/resources/repository.rb:116:in `upload'
      # ./spec/unit/resources/repository_spec.rb:147:in `block (4 levels) in <module:Artifactory>'

  13) Artifactory::Resource::Repository#upload when the artifact is a file path PUTs the file at the path to the server
      Failure/Error: file     = File.new(File.expand_path(local_path))

        #<File (class)> received :new with unexpected arguments
          expected: ("/fake/path")
               got: ("D:/fake/path")
         Please stub a default value first if message might be received with other args as well.
      # ./lib/artifactory/resources/artifact.rb:533:in `upload'
      # ./lib/artifactory/resources/repository.rb:116:in `upload'
      # ./spec/unit/resources/repository_spec.rb:139:in `block (4 levels) in <module:Artifactory>'

Finished in 1.82 seconds (files took 1.26 seconds to load)
197 examples, 13 failures

Failed examples:

rspec ./spec/unit/resources/artifact_spec.rb:60 # Artifactory::Resource::Artifact#upload when the md5 is available PUTs the file with the checksum headers set
rspec ./spec/unit/resources/artifact_spec.rb:93 # Artifactory::Resource::Artifact#upload when matrix properties are given converts "+" to "%2B"
rspec ./spec/unit/resources/artifact_spec.rb:76 # Artifactory::Resource::Artifact#upload when matrix properties are given converts the hash into matrix properties
rspec ./spec/unit/resources/artifact_spec.rb:85 # Artifactory::Resource::Artifact#upload when matrix properties are given converts spaces to "+" characters
rspec ./spec/unit/resources/artifact_spec.rb:69 # Artifactory::Resource::Artifact#upload when the sha1 is available PUTs the file with the checksum headers set
rspec ./spec/unit/resources/artifact_spec.rb:103 # Artifactory::Resource::Artifact#upload when custom headers are given passes the headers to the client
rspec ./spec/unit/resources/artifact_spec.rb:51 # Artifactory::Resource::Artifact#upload when the artifact is a file path PUTs the file at the path to the server
rspec ./spec/unit/resources/repository_spec.rb:180 # Artifactory::Resource::Repository#upload when custom headers are given passes the headers to the client
rspec ./spec/unit/resources/repository_spec.rb:153 # Artifactory::Resource::Repository#upload when matrix properties are given converts the hash into matrix properties
rspec ./spec/unit/resources/repository_spec.rb:170 # Artifactory::Resource::Repository#upload when matrix properties are given converts "+" to "%2B"
rspec ./spec/unit/resources/repository_spec.rb:162 # Artifactory::Resource::Repository#upload when matrix properties are given converts spaces to "+" characters
rspec ./spec/unit/resources/repository_spec.rb:144 # Artifactory::Resource::Repository#upload when matrix properties are given converts the hash into matrix properties
rspec ./spec/unit/resources/repository_spec.rb:136 # Artifactory::Resource::Repository#upload when the artifact is a file path PUTs the file at the path to the server

Randomized with seed 23668

C:/Ruby22/bin/ruby.exe -I'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib';'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-support-3.4.1/lib' 'C:/Ruby22/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb' --tag ~integration failed
```

**Comment by schisamo** [comment]
Fixed by https://github.com/chef/artifactory-client/pull/80
