### ISSUE TITLE
NoMemoryError: failed to allocate memory on artifact.download()

### ISSUE THREAD

**Issue by Yvangelist01** [chef/artifactory-client#83]
Clueless...please any ideas?
Whenever I try to download a file larger than 300Mb. I get to following error:

Generated at 2017-01-19 06:54:38 -0500
NoMemoryError: failed to allocate memory
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/protocol.rb:102:in `read'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:290:in `block in read_body_0'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:275:in `inflater'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:280:in `read_body_0'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:226:in `body'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:163:in `reading_body'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1422:in `transport_request'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:1384:in `request'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/client.rb:246:in `block in request'
C:/opscode/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/client.rb:245:in `request'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/client.rb:102:in `get'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/resources/artifact.rb:493:in `block in download'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/resources/artifact.rb:492:in `open'
C:/Users/theuser/.chefdk/gem/ruby/2.1.0/gems/artifactory-2.5.1/lib/artifactory/resources/artifact.rb:492:in `download

**Comment by Yvangelist01** [comment]
Found the issue but I need a fix.
artifact.rb is not writing the file in chunk as suggested by ruby-doc (http://ruby-doc.org/stdlib-2.4.0/libdoc/net/http/rdoc/Net/HTTP.html)

uri = URI('http://example.com/large_file')

Net::HTTP.start(uri.host, uri.port) do |http|
  request = Net::HTTP::Get.new uri

  http.request request do |response|
    open 'large_file', 'w' do |io|
      response.read_body do |chunk|
        io.write chunk
      end
    end
  end
end
